feat: add navbar
mermelada-tech/netflix-clon pull request #6
Opened 2023-04-25 19:34 UTC by wayaba

## Descripción del cambio ❗

[Descripción detallada del cambio que se ha realizado en el código y por qué es necesario.]

## Solución Propuesta 😎

[Descripción de la solución que se ha implementado en el código.]

## Tipo de cambio 👊

[Marque con una "x" lo que corresponda]

- [ ] Bug fix (solución a un error)
- [ ] Mejora de la funcionalidad
- [ ] Nuevo feature (nueva característica)
- [ ] Cambio en la documentación

## Comprobación 🕵️‍♀️

[Descripción de las pruebas que se han realizado para asegurarse de que el código funciona correctamente.]

## Cómo se ha probado 👩‍💻

[Detalles de las pruebas realizadas, como las versiones de los navegadores o los sistemas operativos utilizados.]

## Capturas de pantalla (opcional) 🙇‍♀️

[Capturas de pantalla que ayuden a entender los cambios realizados, si es necesario.]

## Lista de comprobación 🥰

- [ ] He leído las pautas de contribución.
- [ ] He actualizado la documentación, si es necesario.
- [ ] He añadido pruebas que demuestran que mi cambio funciona.
- [ ] He asegurado que mi código cumple con los estándares del proyecto.
- [ ] He etiquetado el PR correctamente para que sea fácil de encontrar y revisar.

## Notas adicionales 🎀

[Cualquier otra información relevante que el contribuidor quiera añadir, como problemas conocidos o preguntas para el revisor.]

2023-04-25 19:35 UTC, wayaba commented
Subo componente Navbar

2023-05-03 09:30 UTC, nujovich requested changes

2023-05-03 09:30 UTC, nujovich commented on .gitignore
El package-lock.json nunca debería ir en el gitignore!! De esta manera impide que nuevos miembros del equipo obtengan nuestras mismas dependencias dentro de cada entorno local. Inclusive podría romper nuestro CI/CD en algún momento: https://dev.to/adamklein/package-lock-json-in-git-or-not-50l5

2023-05-03 09:30 UTC, nujovich commented on components/AccountMenu.tsx
> +        className="px-3 text-center text-white text-sm hover:underline"
El alert es parte de un debug ?

2023-05-03 10:25 UTC, wayaba commented on components/AccountMenu.tsx
> +        className="px-3 text-center text-white text-sm hover:underline"
El alert es porque ahí debería ir el logout y como no está desarrollado aún, deje el alert a propósito. Lo puedo sacar si queres

2023-05-03 10:26 UTC, wayaba commented on .gitignore
Perdón no sabía eso.

2023-05-05 09:45 UTC, nujovich commented on components/AccountMenu.tsx
> +        className="px-3 text-center text-white text-sm hover:underline"
Dejalo, se completa en otra tarea entonces!

2023-05-05 11:26 UTC, wayaba commented
oki gracias

2023-05-05 12:56 UTC, merged